name: Go

# Any change in triggers needs to be reflected in the concurrency group.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Set up Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: 1.16.4

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Run static checks
      uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.40.1

        # Optional: golangci-lint command line arguments.
        args: --config=.golangci.yml --verbose

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: true

        # Optional: if set to true then the action will use pre-installed Go.
        skip-go-installation: true

        # Optional: if set to true then the action don't cache or restore ~/go/pkg.
        skip-pkg-cache: true

        # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
        skip-build-cache: true

  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Check module vendoring
        run: |
          go mod tidy
          go mod vendor
          go mod verify
          git diff --exit-code
